---
- name: install docker
  yum: name=docker state=present

- name: start the docker service
  service: name=docker enabled=yes state=started

- shell: uname -s
  register: uname_s_result

- debug: msg="**{{ uname_s_result.stdout }}**"

- shell: uname -m
  register: uname_m_result

- debug: msg="************ {{ uname_m_result.stdout }}*******************"

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.0-rc1/docker-compose-{{ uname_s_result.stdout}}-{{ uname_m_result.stdout }}
    dest: /usr/local/bin/docker-compose

- name: change the permissions
  file: path=/usr/local/bin/docker-compose owner=root group=root mode="u+x"

- name: create a softlink
  file: src=/usr/local/bin/docker-compose dest=/usr/bin/docker-compose state=link
